
<?php /** @var \Magento\Framework\View\Element\Template $block */?>
<?php  $customerdata = $block->getViewModel()->getCustomerData();  ?>
<?= $escaper->escapeHtml(__("My First Link Page ")) ?>

<div class="maindiv">
    <div class="secondary">
        Widget Example using Magento 2
    </div>
</div> 
<script type="text/x-magento-init">
    {
        ".maindiv": {
            "myCustomWidget": {
                
            }
        }
    }
</script>

