name: Update README Table
on:
  schedule:
    - cron: '4 * * * *'
  push:
    branches:
      - master
jobs:
  update-table:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Generate and update table
        run: |
          python update_table.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m " chore(readme): Update directory table" || echo "No changes to commit"
          git push
      
