name: Update README Table
on:
  schedule:
    - cron: '4 * * * *'
  push:
    branches:
      - master
jobs:
  update-table:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate and update table
        run: |
          # 1. Generate the table content and save it to a temporary file.
          {
            echo "| Directory | Description |"
            echo "|---|---|"
            find . -maxdepth 1 -type d -not -path './.git' -not -path './.github' -print0 | while IFS= read -r -d '' DIR; do
              DIR_NAME=$(basename "$DIR")
              DESCRIPTION_FILE="$DIR/composer.json"
              if [ -f "$DESCRIPTION_FILE" ]; then
                DESCRIPTION=$(<"$DESCRIPTION_FILE")
              else
                DESCRIPTION="No description available."
              fi
              echo "| [$DIR_NAME]($DIR_NAME) | $DESCRIPTION |"
            done
          } > table_content.md

          # 2. Use sed to replace the content between the markers with the file's content.
          # We use a custom delimiter '%' instead of '/' to avoid conflicts.
          # The 'r' command reads from a file.
          sed -i '//r table_content.md' README.md

          # 3. Clean up the old content and the temporary file.
          sed -i '//,//{//!d;}' README.md
          rm table_content.md


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add README.md
          git diff --staged --quiet || git commit -m "🤖 docs: Auto-update directory table"
          git push
      
