name: Update README Table
on:
  schedule:
    - cron: '4 * * * *'
  push:
    branches:
      - master
jobs:
  update-table:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate and update table
        run: |
          # This script will be run by the GitHub Action
          # It finds directories and creates a markdown table.
          TABLE_CONTENT=$(
            echo "| Directory | Description |"
            echo "|---|---|"
            find . -maxdepth 1 -type d -not -path './.git' -not -path './.github' -print0 | sort -z | while read -d '' DIR; do
              DIR_NAME=$(basename "$DIR")
              # A simple way to get description is from a 'README.md' file in each directory.
              DESCRIPTION_FILE="$DIR/README.md"
              if [ -f "$DESCRIPTION_FILE" ]; then
                DESCRIPTION=$(cat "$DESCRIPTION_FILE")
              else
                DESCRIPTION="No description available."
              fi
              echo "| [$DIR_NAME]($DIR_NAME) | $DESCRIPTION |"
            done
          )

          # Use sed to replace the content between the markers in the README.
          # We're using Perl's sed ('-i.bak' for in-place editing) because macOS's sed is different.
          sed -i.bak '//,//c\\n'"$TABLE_CONTENT"'\n\n' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add README.md
          git diff --staged --quiet || git commit -m "🤖 docs: Auto-update directory table"
          git push
      
